services:
  keycloak-web:
    image: quay.io/keycloak/keycloak:26.3.0
    ports:
      - 8084:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: start-dev
